nos3#100 - Generic Radio
nasa-itc/generic_radio pull request #1
Opened 2023-03-23 13:44 UTC by jlucas9

2023-03-30 17:42 UTC, msuder requested changes

2023-04-03 17:46 UTC, jlucas9 commented on fsw/src/generic_radio_app.c
> +                    OS_printf("0x%02x ", read_data[i]);
I don't believe it can be since we provide that size in the socket_recv call.

2023-04-03 17:48 UTC, jlucas9 commented on fsw/src/generic_radio_device.c
> +    OS_TaskDelay(GENERIC_RADIO_CFG_DEVICE_DELAY_MS);
I don't know of another way except to rely on a blocking socket to avoid eating up all your processor.

2023-04-03 17:49 UTC, jlucas9 commented on sim/src/generic_radio_hardware_model.cpp
Ideally used in the future when improving to determine if in-view of ground stations or other spacecraft for proximity operations.

2023-04-04 11:23 UTC, jlucas9 commented on README.md
> +This generic radio component is a socket based device that accepts multiple commands, including requests for telemetry and data.
Updated https://github.com/nasa/nos3/wiki/NOS3-Component-Development

2023-04-04 11:38 UTC, jlucas9 commented on fsw/src/generic_radio_app.c
> +        case GNEERIC_RADIO_PROXIMITY_CC:
Command count does not increment for ProxmityForward currently as it has its own counter. HK shouldn't increment command counts either.

2023-04-04 16:42 UTC, msuder commented on sim/src/generic_radio_hardware_model.cpp
Agree that they may be used later, but they are not used/tested currently, so they should be deleted.  They are easy enough to recreate later (and there may even be improved template versions by then to create from).

2023-04-12 14:40 UTC, jlucas9 commented on fsw/src/generic_radio_app.c
> +    socket_close(&GENERIC_RADIO_AppData.RadioSocket);
Added proxy close in commit d632baa

2023-04-12 14:41 UTC, jlucas9 commented on fsw/src/generic_radio_app.c
> -        case GENERIC_RADIO_REQ_DATA_TLM:
Resolved in commit d632baa

2023-04-12 14:41 UTC, jlucas9 commented on fsw/src/generic_radio_app.c
> +    status = GENERIC_RADIO_RequestHK(&GENERIC_RADIO_AppData.RadioSocket, (GENERIC_RADIO_Device_HK_tlm_t*) &GENERIC_RADIO_AppData.HkTelemetryPkt.DeviceHK);
Removed in commit d632baa

2023-04-12 14:42 UTC, jlucas9 commented on fsw/src/generic_radio_events.h
> -#define GENERIC_RADIO_REQ_DATA_ERR_EID          32
Resolved in commit d632baa

2023-04-12 14:42 UTC, jlucas9 commented on sim/src/generic_radio_hardware_model.cpp
> +                    _prox_fwd.ip = v.second.get("ip", _prox_fwd.ip);
Resolved in commit d632baa

2023-04-12 14:49 UTC, mgrubb-gsfc approved these changes

2023-04-12 14:50 UTC, merged